### ISSUE TITLE
Offer benchmark comparison to memcached and no object cache drop-in

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-redis#100]
In our readme, it would be informative to have some reproducible benchmark comparison between WP Redis, a memcached drop-in, and no persistent object cache.

From https://twitter.com/thespacedmonkey/status/725651015706488832

**Comment by szepeviktor** [comment]
@danielbachhuber Which plugin is your memcached object cache candidate?

**Comment by danielbachhuber** [comment]
https://github.com/tollmanz/wordpress-pecl-memcached-object-cache would be a good one

**Comment by danielbachhuber** [comment]
Punting on this one — not worth the effort at this point.

**Comment by szepeviktor** [comment]
Could you describe the benchmark in one sentence?
Storing keys then reading them??

**Comment by danielbachhuber** [comment]
The benchmark could be to compare load times against a set of common WordPress tasks (e.g. publish a post, read it 100x).

Here's an example of using New Relic for this: https://twitter.com/outlandishjosh/status/775756511611990016
