### ISSUE TITLE
WP Redis v 4.0 performs better on Fedora 22 than v 5.0 for some plugins

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/wp-redis#102]
Reference desk case 62005

It appears that when using WP Redis 5.0 on cacheservers running Fedora 22, it is necessary to click the 'Clear Caches' button in the WP Admin under 'Pantheon cache' in order for pages to render updated content in fields created by the Advance Custom Fields PRO plugin.

There may be other plugins that surface this issue, but this is the first report.

**Comment by danielbachhuber** [comment]
@ttrowell This seems like it may actually be an issue with Advanced Custom Fields Pro. How did the ticket end up?
