### ISSUE TITLE
Info on plugin activation

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#106]
Could we have a line in README on plugin activation?
wp-cli etc.

**Comment by danielbachhuber** [comment]
I'm not sure I follow. A line describing what specifically?

**Comment by szepeviktor** [comment]
e.g.

> You don't need to activate the plugin to use Redis object cache.
> To enable the WP-CLI command you need to activate the plugin.

**Comment by danielbachhuber** [comment]
Will do, see #109

**Comment by szepeviktor** [comment]
OK!
