### ISSUE TITLE
Alloptions race condition

### ISSUE THREAD

**Issue by schrapel** [pantheon-systems/wp-redis#111]
We experience this race condition on high traffic sites with Memcached. Would you accept a PR to solve this? Even if it's just to add a filter to the set function that we can use

https://core.trac.wordpress.org/ticket/31245
https://github.com/tillkruss/Redis-Object-Cache/issues/19

**Comment by danielbachhuber** [comment]
I'll give this some thought.

At this point, I'm not sure it's a problem we want to solve until core decides upon an official direction, though. Why did Till close that issue without discussion?

**Comment by schrapel** [comment]
@danielbachhuber I think he just wanted to provide a solution to the problem. He's involved in the ticket on core too. 

Humanmade solved it in a slightly different way I don't really agree with for the Memcache PECL extension https://github.com/humanmade/memcache-object-cache/blob/master/object-cache.php#L153-L231

I don't necessarily think it's a problem you need to solve since it's a very small user base that are affected by the issue but it would be nice if there was a filter we could call rather than having to apply a patch via Composer.

**Comment by danielbachhuber** [comment]
> I don't necessarily think it's a problem you need to solve since it's a very small user base that are affected by the issue but it would be nice if there was a filter we could call rather than having to apply a patch via Composer.

Ok. Let's leave this issue open for a while before making a decision, to see if anyone else has been affected by this and has an opinion on the matter.

**Comment by danielbachhuber** [comment]
At this point, we're going to wait to support this until there's an official core direction.
