### ISSUE TITLE
Add Multi get / set functions 

### ISSUE THREAD

**Issue by spacedmonkey** [pantheon-systems/wp-redis#112]
I know this one might be a long shot, as the core team I still hashing out the implementation ([details here](https://core.trac.wordpress.org/ticket/20875)) but it doesn't stop us implementing it on drop-in. It is then up to the developer to choose to use them or not. 

Other object cache based drop-ins have done similar, 
- [Example 1](https://github.com/humanmade/memcache-object-cache/blob/master/object-cache.php#L94)
- [Example 2](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/blob/master/object-cache.php#L389)
- [Example 3](https://github.com/ericmann/Redis-Object-Cache/blob/master/object-cache.php#L120)

Redis supports [multi gets](https://github.com/phpredis/phpredis#mget-getmultiple) and [multi sets](https://github.com/phpredis/phpredis#mset-msetnx). It could ever be prefixed, something like this 
`wp_redis_cache_get_multi` to stop conflicts with future core implementations.

**Comment by danielbachhuber** [comment]
> It could ever be prefixed, something like this 
> wp_redis_cache_get_multi to stop conflicts with future core implementations

I'd be amenable to having the functions prefixed.
