### ISSUE TITLE
Allow only some group to delete whole group deletes

### ISSUE THREAD

**Issue by spacedmonkey** [pantheon-systems/wp-redis#113]
When WP_REDIS_USE_CACHE_GROUPS is set to true, then a hash set is used to store keys. However this means that the expires field is then ignored, a ttls are ignored. However there are valid reasons to have ttl on caches and not invalidating them can break many things. There are examples in core where caches should invalidate themselves. Good example is [here](https://github.com/WordPress/WordPress/blob/1036637afcae3725c64a65f8e7a334bb4a94da7d/wp-includes/class-wp-term-query.php#L735). 

A new method be added (similar to wp_cache_add_non_persistent_groups), that allows a developers to define which groups should be allowed to be delete and which group still respect the expire time. 

For example, I would want the cache group of "posts" to allow to deleted, by the terms or batcache group not.

**Comment by danielbachhuber** [comment]
> When WP_REDIS_USE_CACHE_GROUPS is set to true, then a hash set is used to store keys. However this means that the expires field is then ignored, a ttls are ignored.

Correct.

> A new method be added (similar to wp_cache_add_non_persistent_groups), that allows a developers to define which groups should be allowed to be delete and which group still respect the expire time.

I'd be amenable to this, as long as there are good tests and backwards compat for the constant is maintained.

**Comment by danielbachhuber** [comment]
@spacedmonkey In hindsight, I almost regret introducing the constant :( Either whitelisting or blacklisting groups makes much more sense.

I'm leaning towards this behavior:

1. `WP_REDIS_USE_CACHE_GROUPS` enables Redis hashes for all groups.
2. `wp_cache_add_redis_hash_groups()` permits whitelisting Redis hashes for specific groups.

This is different than your originally proposed behavior, which is to blacklist groups after Redis hashes have been globally enabled. It seems more precise, and generally better, to whitelist over blacklist. What do you think?

**Comment by stevector** [comment]
@spacedmonkey, Can you confirm https://github.com/pantheon-systems/wp-redis/pull/137 works as you expect?
