### ISSUE TITLE
Additional CLI commands

### ISSUE THREAD

**Issue by schrapel** [pantheon-systems/wp-redis#117]
- [ ] install - could be used to link or copy the object-cache.php into the wp-content directory
- [x] check - could be used to check everything is installed and working, servers added to wp-config, servers are online and can be authenticated to, etc

If you like the idea of these and had ideas for other commands I can prepare a PR

**Comment by danielbachhuber** [comment]
> could be used to link or copy the object-cache.php into the wp-content directory

I think this should be linking over copying.

> If you like the idea of these and had ideas for other commands I can prepare a PR

Yep, I dig them 👍

**Comment by stevector** [comment]
We currently have a PR open for symlinking upon activation: https://github.com/pantheon-systems/wp-redis/pull/130/files

Those workflows, (symlink with CLI, vs symlink with activation) should not duplicate code.
