### ISSUE TITLE
Redis database selection

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#122]
I know we have cache key salt.
Could we introduce database selection by a constant?
http://www.rediscookbook.org/multiple_databases.html

```php
$redis->select( $database )
```
As in https://github.com/ericmann/Redis-Object-Cache/blob/master/object-cache.php#L345-L347

I am planning to use Redis on a small server with several independent sites.

**Comment by danielbachhuber** [comment]
> Could we introduce database selection by a constant?

Why can't you just do this with a conditional in `wp-config.php` ?

**Comment by szepeviktor** [comment]
What would be the code?

**Comment by szepeviktor** [comment]
I've meant **Redis database** selection.

**Comment by danielbachhuber** [comment]
> I've meant Redis database selection.

Oh, sorry about that. I thought you meant separate Redis instances.

I'd be amenable to adding this feature.

> Could we introduce database selection by a constant?

Given we're already depending on a `$redis_server` global, it's probably best to continue using that, and introduce a new array key called `database`

**Comment by szepeviktor** [comment]
> introduce a new array key called database

OK!

**Comment by szepeviktor** [comment]
This is like a fairy tale.
