### ISSUE TITLE
Symlink the file automatically after activation of the plugin

### ISSUE THREAD

**Issue by shadyvb** [pantheon-systems/wp-redis#126]
Having to copy the file manually can be overridden by the plugin creating a proper symlink like what Query Monitor plugin does ( ref: https://github.com/johnbillion/query-monitor/blob/fc9d34197e359c4c31e940e34c9fa0bf0c1108d6/classes/Activation.php#L40 ).

This makes it easier for people to use the plugin out of the box.

**Comment by danielbachhuber** [comment]
I'd be amenable to this.

**Comment by danielbachhuber** [comment]
Punting on this, for reasons described in https://github.com/pantheon-systems/wp-redis/pull/130#issuecomment-244212633
