### ISSUE TITLE
Add a conditional for when Redis is not available

### ISSUE THREAD

**Issue by shadyvb** [pantheon-systems/wp-redis#127]
The conditional prevents the site from breaking if Redis is not available locally or on some environment. An admin message to inform would be good to have as well.

Would probably work by wrapping the whole `object-cache.php` file in a `class_exists( 'Redis' )` conditional.

**Comment by danielbachhuber** [comment]
> Add a conditional for when Redis is not available

Can you verify you're using the latest version of this plugin? 

We [already have such a conditional](https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L945-L949), so I'd be curious to hear more details about how to reproduce.

**Comment by shadyvb** [comment]
Yeah, you're definitely right, I did download the latest version, but copied the one from an old archive. Classic fail!

Hopefully https://github.com/pantheon-systems/wp-redis/issues/126 would help make sure this doesn't happen again.

Thanks!
