### ISSUE TITLE
AWS Elastic Cache cluster or master/replica

### ISSUE THREAD

**Issue by enricodeleo** [pantheon-systems/wp-redis#155]
Hi everyone!

According to the installation readme, we need to add a "host" to use this plugin out of Pantheon. Since I am on AWS and use their Elastic Cache service for  caching, I am forced to either chose a master/replica or cluster environment for Redis. How can I handle such configuration with wp-redis?

**Comment by danielbachhuber** [comment]
> Since I am on AWS and use their Elastic Cache service for caching, I am forced to either chose a master/replica or cluster environment for Redis. How can I handle such configuration with wp-redis?

Hey @enricodeleo,

Thanks for considering WP Redis. The plugin is fully supported on Pantheon, and available for use by the broader WordPress community. However, we don't offer full support for other infrastructure.

**Comment by enricodeleo** [comment]
@danielbachhuber thank you for your reply. I don't ask for support on the AWS infrastructure per se but I was wandering if this plugin can support other redis scenarios other than a single instance server.

**Comment by danielbachhuber** [comment]
> I was wandering if this plugin can support other redis scenarios other than a single instance server.

Multiple Redis backends isn't something the plugin currently supports.

**Comment by enricodeleo** [comment]
Thank you again for your reply!
