### ISSUE TITLE
Empty database + activated object cache

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#158]
I think this is a more than an edge case.

Is there a solution to install WP with wp-redis without db tables?

Please advise.

**Comment by danielbachhuber** [comment]
@szepeviktor Sorry for the late reply here. Are you still looking for an answer?

**Comment by szepeviktor** [comment]
OK.

1. Download WordPress and configure
1. Download wp-redis and put the drop-in in place
1. How to install WordPress now?

Actually I was cloning a WP install and left the drop-in in place. It caused an installation error.

**Comment by danielbachhuber** [comment]
> Actually I was cloning a WP install and left the drop-in in place. It caused an installation error.

What was the installation error?

**Comment by szepeviktor** [comment]
Yes.

**Comment by szepeviktor** [comment]
I am very sorry.
I remember this way: I've left the same `WP_CACHE_KEY_SALT` and haven't cleaned the object cache.

**Comment by danielbachhuber** [comment]
👍
