### ISSUE TITLE
Caching works only when user is logged into WP

### ISSUE THREAD

**Issue by ThailandCat** [pantheon-systems/wp-redis#166]
When no users logged the caching is not work.

**Comment by danielbachhuber** [comment]
Hi @ThailandCat,

Thanks for the report! Could you share details on how to reproduce on a fresh WordPress install and no other plugins active?

**Comment by ThailandCat** [comment]
Hi, to reproduce

Ubuntu 16.04.1 Server latest with updates I run locally on VPS with 1vCPU/2GB RAM/ 20 GB SSD
WP 4.7 latest
Redis 3.0.6 from official Ubuntu repo + PECL Redis from official repo (no any 3-rd party PPA)
Configuration for non-Pantheon systems according to manual added to wp-config.php 

As I see in redis-cli , actually the caching works but maybe 4-5 times slower, when no user is logged. 
When user logged, caching is lighting - fast.
If possible to debug further, or need additional info, please tell how, I will try to provide additional info

Thank you so much!

**Comment by danielbachhuber** [comment]
Just to confirm, this is a stock install of WordPress with no plugins activated and using the Twenty Seventeen theme?

**Comment by ThailandCat** [comment]
Yes, stock and I tried with default Twenty Sixteen and custom The7 theme.

**Comment by danielbachhuber** [comment]
Very odd. Can you share a screencast of the behavior you're seeing so I can better wrap my head around what you're experiencing?
