### ISSUE TITLE
Interoperability of `bad-actor` cache group

### ISSUE THREAD

**Issue by JJJ** [pantheon-systems/wp-redis#170]
I love the idea of the `bad-actor` cache group handling.

Any interest in trying to work this upstream and/or into other caching plugins? I can start with WP Spider Cache, myself.

**Comment by danielbachhuber** [comment]
Just to make sure we're on the same page, could you explain in a bit more detail? Any specifics of issues you've run into would be helpful.

**Comment by JJJ** [comment]
Ha. Clearly, I was confused. I misinterpreted the readme comment to mean that the `bad-actor` cache group was a literally supported black-hole for bypassing the cache entirely.

Disregard.

**Comment by danielbachhuber** [comment]
Hahahahaha. Best GitHub reply I've ever had.

**Comment by JJJ** [comment]
I _really_ know how to party.
