### ISSUE TITLE
Wordpress 4.7.1 - Increase in redis-get and redis-setex

### ISSUE THREAD

**Issue by andyphillips82** [pantheon-systems/wp-redis#171]
Hi, 

We just upgraded from 4.7.1 from 4.6.2 and had a massive increase in redis-get and redis-setex commands.

Have you seen this before?

**Comment by danielbachhuber** [comment]
I haven't seen it, no.

Few questions to help you dig further:

* Was it an increase for a specific period of time, or ongoing?
* Did you make any plugin updates, etc. at the same time as the WordPress update?
* How are you monitoring calls? Any chance you can get a backtrace in there so you can see where the calls are being made from?

**Comment by andyphillips82** [comment]
Right, plugins!  We're starting to roll them back one by one.

I'm guessing it's either ACF, Yoast, or Stream.

It's a ongoing increase.

Using NewRelic, which doesn't show us the source.  And when we monitor our redis instance, the logs are just so full of stuff it's hard to tell.

**Comment by danielbachhuber** [comment]
> I'm guessing it's either ACF, Yoast, or Stream.

I think ACF might be the culprit. ACF was the genesis of #97

> We just upgraded from 4.7.1 from 4.6.2 

Make sure you're running 4.7.2, as 4.7.1 and 4.7 have a 9 out of 10 security issue.

**Comment by andyphillips82** [comment]
Yeah sorry, I mistyped.   4.7.2 is what we're one.

Just downgraded ACF to a previous version, no affect.

**Comment by danielbachhuber** [comment]
Ok. Another debugging suggestion would be to use `redis-cli` and run `KEYS *` to see what keys are being saved. From that, you can do some grepping of your codebase to see where the keys are coming from.

This seems like a problem specific to your environment though, and not something specific to WP Redis.

**Comment by andyphillips82** [comment]
Yup, thanks for the help!  We'll continue to debug.

**Comment by szepeviktor** [comment]
@andyphillips82 I was also going through the process of evaluating plugins.
ACF is sadly a *popular-type* plugin.
Here are some enterprise plugins:
- CMB2
- https://github.com/alleyinteractive/wordpress-fieldmanager
- https://github.com/sc0ttkclark/wordpress-fields-api
- for page-specific content: https://github.com/wp-shortcake/shortcake

**Comment by andyphillips82** [comment]
Yeah, it's definitely expensive. What we're seeing NewRelic is truly bizarre.

We have some randomly named Hooks that have all of a sudden cropped up and firing millions of times.  DB values that seems to be dynamically assigned to hooks.

**Comment by pySilver** [comment]
@andyphillips82 what was the reason? is that ACF?
