### ISSUE TITLE
flush wp_options cache

### ISSUE THREAD

**Issue by mihdan** [pantheon-systems/wp-redis#174]
```php
<?php
function mihdan_redis_flush_cache() {
	wp_cache_flush( ?????? );
}
add_action( 'update_option_public_post_preview', 'mihdan_redis_flush_cache' );
```

How to clear cache for specific option/all options?

**Comment by danielbachhuber** [comment]
> How to clear cache for specific option/all options?

I'm not sure I follow. Could you share what you're trying to do with a bit more detail?

**Comment by mihdan** [comment]
https://monosnap.com/file/HsRFaaocXoTyq53MvCzaCDbGN1lCYH#

**Comment by danielbachhuber** [comment]
@mihdan Based on your screencast, I'm assuming you're referring to the behavior of the "Public Post Preview" checkbox becoming unticked when you save the post. If this is the case, I think there's a bug somewhere in your environment — it shouldn't require extra code for the checkbox to remain ticked.

To help you debug further:

* Does the problem occur when you've removed the WP Redis plugin, or use a different object cache drop-in?
* Can you try disabling the other plugins you're using one by one to see if one of them is causing the issue?

**Comment by mihdan** [comment]
> Does the problem occur when you've removed the WP Redis plugin, or use a different object cache drop-in?

no

> Can you try disabling the other plugins you're using one by one to see if one of them is causing the issue?

The problem remains when you turn off all plug-ins

PS: sorry for my English, i from Russia

**Comment by danielbachhuber** [comment]
Ok. At this point, it's difficult to help you debug further without having access to your system, which is outside the scope of the support we offer.
