### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'RedisException' after update do 0.6.1

### ISSUE THREAD

**Issue by moisb** [pantheon-systems/wp-redis#175]
Hello, yesterday I updated the plugin from version 0.6.0 to 0.6.1, and today the server started to have stability problems.
I have identified several errors in the nginx log:

`2017/04/06 16:17:41 [error] 592#592: *3398503 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection lost' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0" while reading upstream, client: 66.249.64.47, server: mywebsite.com, request: "GET /como-conseguir-desconto-em-passaportes-beto-carrero-world/amp/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.mywebsite.com"
2017/04/06 16:19:03 [error] 592#592: *3398683 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection' in /var/www/mywebsite.com/htdocs/wp-content/object-cache.php:1073
Stack trace:
#0 [internal function]: Redis->get('mywebsite.co...')
#1 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(1073): call_user_func_array(Array, Array)
#2 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(622): WP_Object_Cache->_call_redis('get', 'mywebsite.co...')
#3 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(130): WP_Object_Cache->get('wlt_banners', 'options', false, NULL)
#4 /var/www/mywebsite.com/htdocs/wp-includes/option.php(88): wp_cache_get('wlt_banners', 'options')
#5 /var/www/mywebsite.com/htdocs/wp-content/themes/CP/framework/class/class_core.php(2303): get_option('wlt_banners')
#6 /var/www/mywebsite.com/htdocs/wp-content/themes/template_mywebsite/header.php(158): white_label_themes->BANNER('full_top')
#7 /var/www/mywebsite.com/h" while reading response header from upstream, client: 64.237.49.203, server: mywebsite.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.mywebsite.com"
`
I temporarily deactivated the plugin until I discovered what is causing it

**Comment by danielbachhuber** [comment]
> Hello, yesterday I updated the plugin from version 0.6.0 to 0.6.1, and today the server started to have stability problems.

The 0.6.1 release had insignificant changes, so I suspect this is correlation, not causation.

Did you make other changes to the website in this time period?

> I have identified several errors in the nginx log:

This is the key error:

```
"PHP message: PHP Fatal error: Uncaught exception 'RedisException' with message 'Connection lost'
```

It appears your Redis instance is either getting overwhelmed, or is having stability issues.

Is your site seeing more traffic than it normally does? Or, any ideas where the infrastructure issues might be coming from?
