### ISSUE TITLE
Invalidation

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#176]
I am developing a [.mo file cache](https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/tiny-translation-cache.php) and there is the problem of invalidation.

It is not possible to list keys although I can use `delete_group()` but is specific to Redis - not in WordPress.

Would it be possible to flush all keys on these hooks controlled by a constant? (WP_REDIS_MAINTENANCE_FLUSH)
- 'upgrader_process_complete'
- 'switch_theme'
- 'activate_plugin'
- 'deactivate_plugin'

**Comment by danielbachhuber** [comment]
> Would it be possible to flush all keys on these hooks controlled by a constant? (WP_REDIS_MAINTENANCE_FLUSH)

I'm not sure this is a good fit for the plugin. Can you explain why all keys need to be flushed on these events?

**Comment by szepeviktor** [comment]
Core flushes the cache on upgrade. 
I think it is unknown what happens (and what values stucks in) on plugin de/activation. 
So to be sure we may flush the whole cache.


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by danielbachhuber** [comment]
I don't think it makes sense to diverge from core behavior. You're welcome to write an add-on plugin that flushes the entire cache for those events.

**Comment by szepeviktor** [comment]
Here it is
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-cache-flush-on-maintenance/cache-flush-on-maintenance.php

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
