### ISSUE TITLE
Copying code

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#180]
I am experimenting with MySQL based object caching using the [MEMORY engine](https://dev.mysql.com/doc/refman/5.7/en/memory-storage-engine.html).
I am starting with wp-redis' code and rewriting some parts.

Read would be
```sql
CREATE TABLE IF NOT EXISTS `wp_memory_cache` (
  `grp` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `part` smallint(5) unsigned DEFAULT NULL,
  `data` varchar(21500) NOT NULL,
  `ttl` timestamp NULL DEFAULT NULL
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

SELECT GROUP_CONCAT(`data` ORDER BY `part` SEPARATOR "")
    FROM `wp_memory_cache`
    WHERE (ISNULL(`ttl`) OR `ttl` > NOW())
    GROUP BY `grp`,`id`
    ORDER BY `part`;
```

Comments are welcome!

**Comment by danielbachhuber** [comment]
Have you seen WP LCache? https://github.com/lcache/wp-lcache

The L2 implementation is essentially what you want to do

**Comment by szepeviktor** [comment]
Yes.

> APCu is persistent through the life of a PHP-FPM process. 

On *cheap* shared hosting environments the PHP process dies at shutdown.

Is it possible to use Lcache without APCu?

**Comment by danielbachhuber** [comment]
> Is it possible to use LCache without APCu?

Architecturally yes, but there isn't a non-APCu implementation yet.

**Comment by szepeviktor** [comment]
Thank you!

**Comment by szepeviktor** [comment]
For anyone thinking about this type of cache:
Reading a 101,012 bytes long string takes **2.156** milliseconds.
