### ISSUE TITLE
Atomic append

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#190]
Hello!

I need to store what items (in this case nav menus) are cached. So it is necessary to append the ID to a list.
It would be nice to have an atomic append function which does get+append+set with Redis `APPEND`.
`wp_cache_append( $key, $data, $group = '' );`

**Comment by danielbachhuber** [comment]
This object cache drop-in typically only implements features available in the core object cache.

Is there a reason you need `wp_cache_append()` implemented in this plugin? Could you create a secondary plugin, or simply implement it in your project?

**Comment by szepeviktor** [comment]
Thank you.

Could you describe what a secondary plugin means?

**Comment by danielbachhuber** [comment]
> Could you describe what a secondary plugin means?

To create a second plugin that implements `wp_cache_append()`. You could then install the second plugin in any environment you install WP Redis.

**Comment by szepeviktor** [comment]
Thanks.
