### ISSUE TITLE
Allow support for user sessions

### ISSUE THREAD

**Issue by matthewsuan** [pantheon-systems/wp-redis#191]
Right now, this plugin only saves object cache data into redis.

But wordpress saves the user session tokens into the usermeta table. 

Do you have plans to support saving user session tokens into redis?

Thanks!

**Comment by danielbachhuber** [comment]
> Do you have plans to support saving user session tokens into redis?

No plans, as this is specifically an object cache drop-in. You're welcome to write your own integration though.

**Comment by matthewsuan** [comment]
Ok thanks!

Good job on the plugin.
