### ISSUE TITLE
Slow update to WP Dashboard "There are x comments in your spam queue right now."

### ISSUE THREAD

**Issue by laserjobs** [pantheon-systems/wp-redis#193]
I noticed that "There are x comments in your spam queue right now." does not update for awhile. If I go to the spam comments a lot of the time there is more listed than shown on the WP Dashboard.

**Comment by danielbachhuber** [comment]
Hi @laserjobs,

Thanks for the report. I believe this issue is specific to WordPress, not WP Redis. For whatever reason, the spam comment count cache isn't being updated.

Let us know if you track down reproduction steps specific to WP Redis and we'd be happy to look further.

**Comment by laserjobs** [comment]
It does not happen with Redis Object Cache enabled in W3 Total Cache with the default settings. I am thinking it has something to do with setting "counts" to non-persistent or caching disabled for wp-admin requests . Not sure what method would be correct but I am guessing WP Redis is better coded.

Non-persistent groups:
comment
counts
plugins

**Comment by laserjobs** [comment]
Just an FYI:
It looks like everything is functioning with a 3600 second fetch and W3 Total cache is not caching counts.

Akismet
class.akismet-admin.php
Line 640


// Total spam in queue
--
// get_option( 'akismet_spam_count' ) is the total caught ever
public static function get_spam_count( $type = false ) {
global $wpdb;
 
if ( !$type ) { // total
$count = wp_cache_get( 'akismet_spam_count', 'widget' );
if ( false === $count ) {
if ( function_exists('wp_count_comments') ) {
$count = wp_count_comments();
$count = $count->spam;
} else {
$count = (int) $wpdb->get_var("SELECT COUNT(comment_ID) FROM {$wpdb->comments} WHERE comment_approved = 'spam'");
}
wp_cache_set( 'akismet_spam_count', $count, 'widget', 3600 );
}
return $count;
} elseif ( 'comments' == $type \|\| 'comment' == $type ) { // comments
$type = '';
}
 
return (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(comment_ID) FROM {$wpdb->comments} WHERE comment_approved = 'spam' AND comment_type = %s", $type ) );
}
