### ISSUE TITLE
Add ability to use Predis for SSL endpoints

### ISSUE THREAD

**Issue by nathanielks** [pantheon-systems/wp-redis#194]
Hiya, team!

I wanted to reach out and kick the ball around a bit before I got started on this. I was going to extend `wp-redis` to support Predis because I need the ability to use SSL endpoints with Redis. Is this something y'all would be interested in?

**Comment by danielbachhuber** [comment]
Thanks for the offer, @nathanielks. 

We'd potentially be interested in supporting Predis if it didn't add too much maintenance complexity. It may mostly be a matter of offering an alternate instantiation mode, and then making slightly different calls when `_call_redis()` is executed.

Why don't you submit a pull request and we can discuss from there? Worst case scenario is that you need to put the code you've written into a separate repo. It'll be much easier to have this conversation once we can understand what's actually involved.

**Comment by nathanielks** [comment]
@danielbachhuber sounds like a plan! My desire would be that the Redis backend could be pluggable, so I would update this repo to allow me to select which Redis client I want to use and then add Predis as a separate package.

**Comment by danielbachhuber** [comment]
> My desire would be that the Redis backend could be pluggable, so I would update this repo to allow me to select which Redis client I want to use and then add Predis as a separate package.

Yes, this makes most sense to me.

**Comment by joshkoenig** [comment]
Connecting via TLS is a good reason to support predis. Maybe we should consider making that our default! 

+1 for keeping the complexity down and making sure we can easily unit test w/both.

**Comment by nathanielks** [comment]
Excited to get started on this!

**Comment by nathanielks** [comment]
Resolved in https://github.com/pantheon-systems/wp-redis/pull/196

**Comment by nathanielks** [comment]
> +1 for keeping the complexity down and making sure we can easily unit test w/both.

sure thing, @joshkoenig!
