### ISSUE TITLE
Direct WPDB Query not triggering cache deletion?

### ISSUE THREAD

**Issue by vincent-lu** [pantheon-systems/wp-redis#195]
Hi I've been using this plugin in production for about a month now. Recently we noticed one of the CPT's `post_status` are displaying incorrectly in backend (backend say post status is Draft even when it is `publish` in database).

It seems code like below won't trigger the cache to bust:
```
global $wpdb;

$wpdb->query("
    UPDATE $wpdb->posts
    SET post_status = 'publish'
    WHERE ID IN (1, 2, 3, 4)
");
```

I guess this is normal as `WHERE ID IN (1, 2, 3, 4)` is just not detected/handled by `wp-redis`. If I use something like `wp_update_post()` the cache will get updated correctly; is my assumption correct?

If it is, is there a place where I can find out what other conditions would cause similar issues (what about `TRUNCATE TABLE` for example, does it trigger cache update)? What is the TTL for the object caches (seems the cache we have for the post status never expired so far)?

Many thanks.

**Comment by danielbachhuber** [comment]
> I guess this is normal as `WHERE ID IN (1, 2, 3, 4)` is just not detected/handled by wp-redis. If I use something like `wp_update_post()` the cache will get updated correctly; is my assumption correct?

Yes, your assumption is correct. `wp_update_post()` calls [`clean_post_cache()`](https://developer.wordpress.org/reference/functions/clean_post_cache/), which then calls `wp_cache_delete()` on the appropriate cache key. 

You can use your existing SQL code as long as you then call `clean_post_cache()` for each post ID.

> If it is, is there a place where I can find out what other conditions would cause similar issues (what about `TRUNCATE TABLE` for example, does it trigger cache update)?

Generally, any time you use direct SQL queries, you'll need to make sure to also purge the appropriate cache bucket. If you use standard WordPress APIs (e.g. `wp_insert_post()`, `wp_update_term()`), then WordPress will take care of clearing the cache for you.

> What is the TTL for the object caches (seems the cache we have for the post status never expired so far)?

The default TTL is "no expiration". This is typically configurable with all of the [cache write functions](https://developer.wordpress.org/reference/functions/wp_cache_set/).

Hope this helps clarify. Feel free to follow up with additional questions if you have them.

**Comment by vincent-lu** [comment]
Thanks @danielbachhuber that makes a lot of sense.

Is there a way to set a default TTL for all object caches?

**Comment by danielbachhuber** [comment]
> Is there a way to set a default TTL for all object caches?

There isn't an interface for it, no. You'd need to likely modify the `object-cache.php` to use some different default value when no value was explicitly provided.

However, I'd encourage you to examine your problem when you're thinking about setting a default TTL. A default TTL of "no expire" _should_ be fine for your system if your system is correctly purging the object cache when it needs to be. If it's not, then you should track down why it's not.

**Comment by vincent-lu** [comment]
Yeah I agree with what you are saying.

It's just considering how varied WordPress plugins can be, having a non-permanent TTL would let me sleep better. I can vet all the plugins we use now but one day one plugin update might sneak thru some code that doesn't trigger cache purging and who knows what kind of damage it can do.

Would be nice if `wp-redis`'s `object-cache.php` can detect default TTL (say, via a const such as `WP_REDIS_OBJECT_CACHE_DEFAULT_TTL`, use its value if its defined, otherwise fallback to 0). If you prefer I can do a PR. But if I'm not mistaken its just add one line to `wp_cache_add()`, `wp_cache_replace()` and `wp_cache_set()`. The line could be as simple as:

```
$expire = defined( 'WP_REDIS_OBJECT_CACHE_DEFAULT_TTL' ) && $expire === 0 ? WP_REDIS_OBJECT_CACHE_DEFAULT_TTL : $expire;
```

**Comment by danielbachhuber** [comment]
> Would be nice if wp-redis's object-cache.php can detect default TTL (say, via a const such as WP_REDIS_OBJECT_CACHE_DEFAULT_TTL, use its value if its defined, otherwise fallback to 0).

Probably not going to happen but you're welcome to maintain a fork. You can always achieve similar by periodically flushing the entire cache. I wouldn't recommend this though, as it will negatively impact performance.

**Comment by vincent-lu** [comment]
Yeah all good thanks @danielbachhuber, appreciate it.
