### ISSUE TITLE
what is Pantheon? 

### ISSUE THREAD

**Issue by xkungfu** [pantheon-systems/wp-redis#203]
sorry, I am new user.

what is Pantheon? 
wp-redis must be based on Pantheon?

**Comment by danielbachhuber** [comment]
> what is Pantheon?

Pantheon is a WordPress & Drupal hosting company: https://pantheon.io/

> wp-redis must be based on Pantheon?

No, it's not a requirement. WP Redis will work in any environment with Redis available.

**Comment by xkungfu** [comment]
I see.
thanks!
