### ISSUE TITLE
Redis Cluster Support

### ISSUE THREAD

**Issue by michaelryanmcneill** [pantheon-systems/wp-redis#206]
Does this plugin support a Redis Cluster implementation? I plan to test myself, but didn’t see mention of clustering support, so I figured I’d ask to see if others (or the maintainers) had previously used this in a Redis Cluster environment.

**Comment by danielbachhuber** [comment]
I don't have any personal experience with Redis Cluster, sorry.

How is a Redis cluster implementation different than a standard Redis instance?

**Comment by michaelryanmcneill** [comment]
There is a standard that explains it in deeply technical details: https://redis.io/topics/cluster-spec

The gist of is that you gain ability to automatically split your dataset among multiple nodes and get a slightly more highly-available setup that is able to handle minor outages. 

Both are big wins for us as we have a multi-site, multi-network, and multi-environment setup that has more than 13,000 total sites that is constantly getting larger and larger.

**Comment by danielbachhuber** [comment]
> The gist of is that you gain ability to automatically split your dataset among multiple nodes and get a slightly more highly-available setup that is able to handle minor outages.

Makes sense.

> Both are big wins for us as we have a multi-site, multi-network, and multi-environment setup that has more than 13,000 total sites that is constantly getting larger and larger

Is this hosted on Pantheon?

**Comment by michaelryanmcneill** [comment]
Nope, we host everything on campus in our own data centers.

**Comment by danielbachhuber** [comment]
Ok, sounds good. We'd be interested to hear how your deployment works out.
