### ISSUE TITLE
Flush only our keys

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#212]
Sometime there are more than one WordPress installation is using the same db:

`sprintf( "EVAL \"return redis.call('del', unpack(redis.call('keys', ARGV[1])))\" 0 %s:*", WP_CACHE_KEY_SALT );`

Would it make sense?

**Comment by danielbachhuber** [comment]
> Sometime there are more than one WordPress installation is using the same db:

Why not switch them to separate databases?

> Would it make sense?

I'm not convinced it makes sense to change the current behavior, as it's similar to how the memcached-based drop-ins behave.

**Comment by szepeviktor** [comment]
> Why not switch them to separate databases?

Do we have `FLUSHDB` in wp-redis?

> I'm not convinced it makes sense to change the current behavior, as it's similar to how the memcached-based drop-ins behave.

I mean to provide another version of flush, something like: flush-prefixed

**Comment by danielbachhuber** [comment]
> Do we have `FLUSHDB` in wp-redis' cli command or in wp-cli?

Hm, not currently.

> I mean to provide another version of flush, something like: flush-prefixed

Could make sense.

**Comment by danielbachhuber** [comment]
Probably makes most sense to implement this on your own for now.
