### ISSUE TITLE
Redis::connect(): connect() failed: Connection timed out in...

### ISSUE THREAD

**Issue by leventmuslim** [pantheon-systems/wp-redis#213]
I get the below error while I try to activate Redis on my dev-site. I assume it  happened after creating _htdocs/wp-content/object-cache.php_ file. What should I do next? 

BTW, line #1105 in the warning is this; "$client_parameters['retry_interval']"

> Warning: Redis::connect(): connect() failed: Connection timed out in /srv/bindings/b0324fb8e647424197a16ac06fb0df4f/code/wp-content/plugins/wp-redis/object-cache.php on line 1105

### https://github.com/pantheon-systems/wp-redis/blob/7bbd8cbe2c8da42c4da5ffabe70f1d6899ba3267/object-cache.php#L1105

**Comment by danielbachhuber** [comment]
Based on the error, it seems like WordPress can't connect to Redis.

Can you try using the same connection credentials with Redis CLI?

**Comment by leventmuslim** [comment]
Sure I’ll try thanks.  It also alerts “Pantheon Redis service needs to be enabled before WP Redis object cache will function properly.” 

Any chance that they are both related warnings?

**Comment by danielbachhuber** [comment]
Yes. In that case, you'll need to follow these instructions: https://pantheon.io/docs/wordpress-redis/#enable-redis-on-the-pantheon-site-dashboard

**Comment by leventmuslim** [comment]
Turns out it's my lack of experience.
I dag around for some more help and found that I also needed to activate WP-Redis on Pantheon Dashboard and it works now. Thank you for fast responses Daniel.

_Ps: Can I add quick final info? -just in case someone gets the same warning
content/object-cache.php file permissions should be set to 644_

**Comment by danielbachhuber** [comment]
> I dag around for some more help and found that I also needed to activate WP-Redis on Pantheon Dashboard and it looks good now.

Great, glad you got it sorted out.

> Ps: Can I add quick final info? -just in case someone gets the same warning
content/object-cache.php file permissions should be set to 644

What were your file permissions set to, and how did they get that way?

**Comment by leventmuslim** [comment]
Did I misinterpret something that I read online, to make WP-Redis work properly? 

I'd used Filezilla and created the object-cache.php through its interface
The file permissions were initially set to 777(xxx), then I changed them to 644

**Comment by danielbachhuber** [comment]
Ah, that makes sense.
