### ISSUE TITLE
Recommended cache invalidation strategy

### ISSUE THREAD

**Issue by vincent-lu** [pantheon-systems/wp-redis#224]
Hi guys, again, thanks for the awesome work put into this plugin.

We've been using this plugin with great success for a while; but I'd like to get some official takes on what's the best way to handle cache invalidation.

So far when I realised I need to invalidate the object cache, I just do a `flushall` on our redis - and this is probably not the most efficient method but it works.

Usually this happens after one of the two things:
1. Activating/deactivating plugins
2. I manually updated database with direct query on mysql (fairly rare, but happens)

So in the above situations, what's the recommended way to bust outdated cache?

A further concern regarding cache invalidation is that because we just recently moved onto immutable deployment on AWS: there is a short time period during deployment, when both old instances and new instances are serving the traffic (all connecting to a centralised redis server), this makes me fairly paranoid about incorrect cache being used and lead to unexpected behaviour. Would appreciate any ideas & recommendations on how to solve this problem.

**Comment by danielbachhuber** [comment]
Hey @vincent-lu,

Great question — to which I'm not sure there's a perfect answer.

Generally, `flushall` is the most reliable for completely invalidating the cache. However, this is likely inadvisable on a high-traffic site.

Without knowing the specifics of your implementation, the two approaches I would consider are:

1. Flushing the `alloptions` cache on deploy, as this is most likely to contain plugin configuration details, etc.
2. Using native WP APIs to flush cache after making direct SQL queries (e.g. `clean_post_cache()` to clean a post cache after updating it).

> A further concern regarding cache invalidation is that because we just recently moved onto immutable deployment on AWS: there is a short time period during deployment, when both old instances and new instances are serving the traffic (all connecting to a centralised redis server), this makes me fairly paranoid about incorrect cache being used and lead to unexpected behaviour. Would appreciate any ideas & recommendations on how to solve this problem.

It seems like the old instance and new instance need to use separate caches. You could define `WP_CACHE_KEY_SALT` to some unique value for each deploy. This will let the same Redis backend handle two distinct cache buckets.

**Comment by vincent-lu** [comment]
Thanks @danielbachhuber, separating cache prefix is a genius move.
