### ISSUE TITLE
[This is not an issue] I am creating REST Only Wordpress Site

### ISSUE THREAD

**Issue by SumeetGohil** [pantheon-systems/wp-redis#225]
Hey There,

I am starting with one of Wordpress Setup with Only REST & Redis. host it to Pantheon, had search for this information but could not find it. does WP Redis support caching WP-JSON (REST) ?

Thanks in advance.

**Comment by danielbachhuber** [comment]
Hi @SumeetGohil,

WP Redis does work with the WP REST API for the purposes of object caching. For full-page caching, you'll want to use Pantheon Advanced Page Cache https://wordpress.org/plugins/pantheon-advanced-page-cache/

Hope this helps. Feel free to follow up with any clarifying questions.
