### ISSUE TITLE
Possible to handle Uncaught RedisException: OOM command not allowed when used memory > 'maxmemory'?

### ISSUE THREAD

**Issue by jonathanstegall** [pantheon-systems/wp-redis#227]
We're not running on Pantheon, but we regularly have periods where we encounter this error.

Here's an example of a log entry:

```
PHP Fatal error:  Uncaught RedisException: OOM command not allowed when used memory > 'maxmemory'. in /wp-content/plugins/wp-redis/object-cache.php:1161\nStack trace:\n#0 /wp-content/plugins/wp-redis/object-cache.php(1161): Redis->setex('transient:mp_me...', 86400, 'a:728586:{i:0;s...')\n#1 /wp-content/plugins/wp-redis/object-cache.php(779): WP_Object_Cache->_call_redis('setex', 'transient:mp_me...', 86400, 'a:728586:{i:0;s...')\n#2 /wp-content/plugins/wp-redis/object-cache.php(191): WP_Object_Cache->set('mp_mem_transien...', 'a:728586:{i:0;s...', 'transient', 86400)\n#3 /wp-includes/option.php(756): wp_cache_set('mp_mem_transien...', Array, 'transient', 86400)\n#4 /wp-content/plugins/minnpost-membership/classes/class-minnpost-membership-cache.php(117): set_transient('mp_mem_transien...', Array, 86400)\n#5 /wp-content/plugins/minnpost-member in /var/www/minnpost.com/htdocs/wp-content/plugins/wp-redis/object-cache.php on line 1161
```

Of course it could be something to do with the minnpost-membership plugin we run, but it also happens with several other plugins (Co-Authors Plus, Popup Maker, The Events Calendar, Elasticpress for example). In any case, it doesn't appear to be plugin-specific but memory specific.

I'm way out of my league when it comes to Redis, but wouldn't it be possible to have some kind of fallback if the memory is overloaded rather than the white screen of death and losing data (I've heard from users who lose edits to posts, for example, when this happens)?

**Comment by danielbachhuber** [comment]
> wouldn't it be possible to have some kind of fallback if the memory is overloaded rather than the white screen of death and losing data (I've heard from users who lose edits to posts, for example, when this happens)?

We might be able to catch the exception and gracefully fall back. I'll look when I have some time.

**Comment by danielbachhuber** [comment]
Hi @jonathanstegall,

In looking at this further, I don't think it makes sense for WP Redis to magically fail back in this scenario. The existing fail back code focuses on attempting to reconnect to Redis; if Redis is reporting out of memory, then that's a real problem that should be fixed.

I'd suggest resolving your specific issue in one of these two ways:

1. Increase the memory available to your Redis instance.
2. Identify which plugin might be using the most memory, and use `wp_cache_add_non_persistent_groups` ([ref](https://github.com/pantheon-systems/wp-redis#how-do-i-disable-the-persistent-object-cache-for-a-bad-actor)) to "ban" its cache group from the persistent object cache.

Hope this helps.
