### ISSUE TITLE
Can't connect to remote DB at redislabs.com

### ISSUE THREAD

**Issue by leventmuslim** [pantheon-systems/wp-redis#233]
[If you’re **_not running on Pantheon_**, edit wp-config.php to add your cache credentials](https://wordpress.org/plugins/wp-redis/#installation)

I can't connect to remote redis database.
*Error I see is; _Warning! PHPRedis module is unavailable, which is required by WP Redis object cache*

**Comment by szepeviktor** [comment]
for clarity: WordPress core -> wp-redis plugin -> phpredis PECL extension -> Redis server

So you need a PHP extension.
