### ISSUE TITLE
Fatal error: add_global_groups in combination with ludicrousdb

### ISSUE THREAD

**Issue by killua99** [pantheon-systems/wp-redis#234]
I'm having this error:

```Fatal error: Uncaught Error: Call to a member function add_global_groups() on null in /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/object-cache.php:219 Stack trace: #0 /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/mu-plugins/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php(2021): wp_cache_add_global_groups('ludicrousdb') #1 /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/mu-plugins/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php(1983): LudicrousDB->add_global_group() #2 /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/mu-plugins/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php(1705): LudicrousDB->tcp_cache_get('10.128.15.224:2...') #3 /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/mu-plugins/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php(667): LudicrousDB->check_tcp_responsiveness('10.128.15.224', '20682', 0.2) #4 /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/mu-plugins/ludicrousdb/ludicrousdb/includ in /srv/bindings/2f59011c99e24ebcb49e35b63989dde1/code/wp-content/object-cache.php on line 219```

It seems to have some connection with https://github.com/stuttter/ludicrousdb/pull/67/files

**Comment by danielbachhuber** [comment]
Sorry for the late reply here, @killua99. Were you able to track this down?

**Comment by killua99** [comment]
I couldn't replicated locally and on Pantheon system we were unable to solve it neither.

From the comment I mentioned  more people seems to have the same problem with Redis on Pantheon and ludicrousdb.

**Comment by danielbachhuber** [comment]
Ok. We'll close this for now and review in greater detail if it comes up in the future. Thanks @killua99

**Comment by ouun** [comment]
I have this issue, too:

`Fatal error: Uncaught Error: Call to a member function add_global_groups() on null in /.../object-cache.php:245`

LudicrousDB calls `wp_cache_add_global_groups( 'ludicrousdb' )`, however the global`$wp_object_cache` is `null` and therefore the error is triggered here: https://github.com/pantheon-systems/wp-redis/blob/cfe3e090ca858cfdfdaee63053bf0b8ac30da7a5/object-cache.php#L241

This happens with `check_tcp_responsiveness` set to `true` while with `false` it does work as expected.

So I am wondering if someone is aware of a workaround or solution.

**Comment by ouun** [comment]
Hi @danielbachhuber,
after I tried to investigate the issue a bit further I ended up with summarizing my findings and opening a new issue in the LudicrousDB repo: https://github.com/stuttter/ludicrousdb/issues/126

Kind regards

**Comment by danielbachhuber** [comment]
Thanks @ouun ! I don't have any immediate answer — it seems to be specific to LudicrousDB. I'll follow along on the other issue.
