### ISSUE TITLE
Clearing cache from WP Admn

### ISSUE THREAD

**Issue by Lunteer** [pantheon-systems/wp-redis#235]
This is probably not an intelligent questions so apologies in advance.

We are using a Wordpress network install. Is there a way to clear the redis cache within the WP Admin area? Is this for all users or just superadmins in the Network admin area?

Thanks in advance!

**Comment by szepeviktor** [comment]
Hello!

I hope you are using WordPress instead of *Wordpress*! :)

wp-redis is a WordPress conform drop-in, so flushing object cache (`wp_cache_flush()`) is enought

- use WP-CLI if you can
- https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-cache-flush-button/flush-cache-button.php - you find 2 other flush plugins there

**Comment by danielbachhuber** [comment]
Thanks @szepeviktor !

@Lunteer Feel free to reply with additional details if you have further questions.

**Comment by Lunteer** [comment]
@szepeviktor Thanks for the answer and thanks for the link! Just not clear if the cache would flush for the one site or the entire network. I thought `wp_cache_flush()` was the entire cache.

@danielbachhuber thanks for closing. I do consider the question answered just want some clarity on the network aspect.

**Comment by szepeviktor** [comment]
@Lunteer I've never met multisite, actually it is a big NO for me, something I should not try.
So all my plugins are totally unaware of network/single site.

**Comment by Lunteer** [comment]
@szepeviktor Thanks. Hopefully someone else can come along and provide more info.

**Comment by danielbachhuber** [comment]
> Just not clear if the cache would flush for the one site or the entire network. I thought `wp_cache_flush()` was the entire cache.

Yes: `wp_cache_flush()` flushes the entire cache. There isn't a way to flush the cache for an individual site.
