### ISSUE TITLE
Difference to the "Redis Object Cache" plugin

### ISSUE THREAD

**Issue by milkovsky** [pantheon-systems/wp-redis#236]
Could you please tell what is difference between this plugin and the "[Redis Object Cache](https://wordpress.org/plugins/redis-cache/#other_notes)" plugin?

As I understand "Redis Object Cache" handles only object cache, and "WP Redis" handles both page and object cache. Is it correct?

**Comment by szepeviktor** [comment]
We don't say anything bad about Till Krüss.

His plugin is more towards non-professional users as it supports Predis (which is in PHP not C)

**Comment by szepeviktor** [comment]
> handles both page and object cache

:( No, both plugins are object cache only.

ps. try not using a full page cache plugin, see https://github.com/szepeviktor/tiny-cache

**Comment by milkovsky** [comment]
Thank you for the feedback and advise!

A follow-up question:
Is there any reason why is the page cache not supported by wp-redis? I think it is in general not a bad idea to store page cache in Redis.

**Comment by szepeviktor** [comment]
AFAIK full page caching is not a professional thing, while comparing highly optimized (https://github.com/szepeviktor/tiny-cache) PHP runtime to HTML file read time you find a small difference (~50 msec)

a full page cache make a lot of things go wrong like HTTP headers, and prevents dynamic content

**Comment by szepeviktor** [comment]
Please close these 2 issues.
Thanks.

**Comment by milkovsky** [comment]
Thank you for the answers!
I am closing the issue.

Next text is just FYI:

I am new to WP, I have Drupal background.
In Drupal there is not separation on Object Cache and Page cache. So I am still not sure what it is all about. In Drupal projects entire cache is stored. With a concept of [cache-tags](https://www.drupal.org/docs/8/api/cache-api/cache-tags) and [cache-contexts](https://www.drupal.org/docs/8/api/cache-api/cache-contexts) cache always stays up-to-date.
There is an optional separation on [dynamic](https://www.drupal.org/docs/8/core/modules/dynamic-page-cache/overview) and not dynamic page cache.

FYI [Redis](https://www.drupal.org/project/redis) module for Drupal.

**Comment by szepeviktor** [comment]
Thank you.

For Drupal site Redis is also a must have.

- I think node content goes to object cache
- HTML output goes to page cache
