### ISSUE TITLE
Difference to W3TC?

### ISSUE THREAD

**Issue by milkovsky** [pantheon-systems/wp-redis#237]
Also what is the difference between this module and [W3TC plugin via Redis](https://www.cloudways.com/blog/install-redis-cache-wordpress/)?

**Comment by szepeviktor** [comment]
@milkovsky This is very good question!

1. wp-redis has well--written code, read it!
1. wp-redis has proper and almost 100% code coverage (tests)
1. wp-redis has Redis-specific features
1. wp-redis is used at Pantheon in high volume
1. wp-redis is [KISS](https://en.wikipedia.org/wiki/KISS_principle) - provides only object cache
1. wp-redis has no UI, so it is the lightest possible

there are many other I miss here

**Comment by milkovsky** [comment]
Thank you! I guess you can add a docu page with comparison of wp-redis with other Redis plugins on the WP market, but it is of course up to you.

**Comment by szepeviktor** [comment]
The intersection of wp-redis and W3TC users are almost zero.
