### ISSUE TITLE
"RedisException: read error on connection" thrown during peak traffic

### ISSUE THREAD

**Issue by vincent-lu** [pantheon-systems/wp-redis#240]
Hi guys we have been using this plugin with great success. But a minor issue is that at times when there is a sudden jump in traffic, our redis server get overwhelmed and we will receive a few of those "RedisException: read error on connection" errors.

I'm wondering what is the best way of managing this issue. Here are some just ideas:

- Allow suppressing this exception from wp-redis (perhaps via an optional define, maybe even define it to only throw this error when it happens at certain frequency)
- Ignore this particular exception at our error reporting infrastructure level (my current solution)
- Beef up the redis server (but our traffic is very "spiky" so I don't think this is particularly suited for us)

Thoughts?

**Comment by danielbachhuber** [comment]
Hey @vincent-lu!

If your Redis server is having capacity issues, then our recommendation would be to add additional capacity. Or, potentially you could change something about your application architecture such that fewer requests are hitting the object cache (e.g. offloading more requests to the full page cache).

Generally, ignoring the error isn't a good idea. It can sometimes even lead to other problems down the road.

**Comment by vincent-lu** [comment]
Thanks @danielbachhuber yeah we will consider doubling up the elasticache instance in our next deployment. Our site is WooCommerce site so by nature the traffic is fairly spiky.

As for the exception itself; if such timeouts happen when wp-redis tries to set cache (and assume there is an old copy of cache in the redis), would the next time wp-redis successfully retrieve the cached data for the key actually get an outdated result?

**Comment by danielbachhuber** [comment]
> As for the exception itself; if such timeouts happen when wp-redis tries to set cache (and assume there is an old copy of cache in the redis), would the next time wp-redis successfully retrieve the cached data for the key actually get an outdated result?

Yes — correct. Which is probably one of the many reasons why simply ignoring the problem isn't a good solution.

**Comment by vincent-lu** [comment]
Makes sense; is there a way to optionally set wp-redis to try to purge that key in such event?

**Comment by danielbachhuber** [comment]
> is there a way to optionally set wp-redis to try to purge that key in such event?

It would require some custom code because WP Redis doesn't keep track of which keys failed to write.

**Comment by vincent-lu** [comment]
Yeah I understand. Would be great to have this option because who knows how many ways a connection could fail...
