### ISSUE TITLE
Question: Load balancing multiple wordpress instances.

### ISSUE THREAD

**Issue by agiz** [pantheon-systems/wp-redis#267]
Hi.

Let's say I have a load balancer sending traffic to two WP instances (same site) each in it's own docker container. One instance can read and write to the DB and to the filesystem, while the other instance is pure slave with just read access to both DB and filesystem.

Do you recommend sharing redis server between two instances or should each instance be connected to their own redis server.

Best,
Ziga

**Comment by danielbachhuber** [comment]
Hi @agiz,

Given the data is shared between the two instances, it'd be fine to share the same Redis server too. A DB write on the first instance should purge the shared cache value.
