### ISSUE TITLE
The organization of the keys in Redis like redis cache

### ISSUE THREAD

**Issue by gurumark** [pantheon-systems/wp-redis#282]
Hello,
Thank you for this plugin.
I am trying to migrate from redis-cache plugin to WP Redis. However, I noticed that by default all the keys are stored at the root level in Redis. How can I organize them nicely under each database (SALT) name so that it is easier to maintain?
![Screenshot (12)](https://user-images.githubusercontent.com/1859151/84570565-51408200-ad5c-11ea-81a4-fa3498c7e7a3.png)
Thank you.

**Comment by gurumark** [comment]
I am also searching for a functionality similar to:
WP_REDIS_SELECTIVE_FLUSH (default: not set)
If set to true, flushing the cache will only delete keys that are prefixed with WP_CACHE_KEY_SALT (instead of emptying the entire Redis database). The selective flush is an atomic O(n) operation.
Any help will be greatly appreciated.

**Comment by danielbachhuber** [comment]
Hi @gurumark:

> However, I noticed that by default all the keys are stored at the root level in Redis. How can I organize them nicely under each database (SALT) name so that it is easier to maintain?

I'm not sure, to be honest! I think that's probably outside the scope of this plugin.

> I am also searching for a functionality similar to:
> WP_REDIS_SELECTIVE_FLUSH (default: not set)
> If set to true, flushing the cache will only delete keys that are prefixed with WP_CACHE_KEY_SALT (instead of emptying the entire Redis database). The selective flush is an atomic O(n) operation.

WP Redis doesn't support this type of selective flush. However, you can connect to a specific Redis database from WordPress, so a comparable alternative would be to use Redis databases for each WordPress installation.
