### ISSUE TITLE
Version 1.1.0 of WP Redis causes the page list on sites running WordPress 5.5 to timeout

### ISSUE THREAD

**Issue by lukecav** [pantheon-systems/wp-redis#291]
The fix was to roll back to version 1.0.1 of WP Redis using WP-CLI.

`wp plugin update wp-redis --version=1.0.1`

The page list in wp-admin would timeout and would not load with WP Redis version 1.1.0 active on the site.
Not sure if the issue is being caused by?
https://github.com/pantheon-systems/wp-redis/pull/287

**Comment by danielbachhuber** [comment]
Thanks for the report, @lukecav.

I'm not able to recreate the problem. Could you share more details about the site (plugins, amount of data), or steps I can follow to reproduce?

**Comment by lukecav** [comment]
wp plugin list --status=active
+-------------------------------------+--------+-----------+---------+
| name                                | status | update    | version |
+-------------------------------------+--------+-----------+---------+
| advanced-custom-fields-pro          | active | none      | 5.8.14  |
| autoptimize                         | active | none      | 2.7.6   |
| cache-enabler                       | active | none      | 1.3.5   |
| custom-post-type-ui                 | active | none      | 1.8.0   |
| ml-slider                           | active | none      | 3.17.0  |
| ninja-forms                         | active | none      | 3.4.25  |
| post-types-order                    | active | none      | 1.9.5.1 |
| stackable-ultimate-gutenberg-blocks | active | none      | 2.9.1   |
| the-events-calendar                 | active | none      | 5.1.5   |
| unique-headers                      | active | none      | 1.7.12  |
| widget-options                      | active | none      | 3.7.4   |
| wp-redis                            | active | available | 1.0.1   |
| wp-youtube-lyte                     | active | none      | 1.7.13  |
| wordpress-seo-premium               | active | none      | 13.3    |
+-------------------------------------+--------+-----------+---------+

**Comment by danielbachhuber** [comment]
Hi @lukecav,

This isn't quite enough information to go on. I'll need enough information to reproduce the issue, or you'll need to do a bit of debugging to identify the root cause.

**Comment by lukecav** [comment]
None of the other active plugins were causing the issue on the page list not loading in wp-admin. Posts and postmeta data levels were not even that high on the site. The same issue happened on another site as well.

**Comment by lukecav** [comment]
`wp_posts` 53.5MB
`wp_postmeta` 111.6MB

**Comment by danielbachhuber** [comment]
> None of the other active plugins were causing the issue on the page list not loading in wp-admin.

Did you try leaving WP Redis active, deactivating all other plugins, and then activating each plugin one by one to see which introduced the slowness?

**Comment by lukecav** [comment]
Yep, I did and none of the plugins being activated one by one resolved the issue.

**Comment by danielbachhuber** [comment]
Ok.

1. When you say "Pages list", what part of the UI are you referring to?
2. Can you enable WP_DEBUG and let me know of any errors you see?

**Comment by lukecav** [comment]
1. **Pages > All Pages** /wp-admin/edit.php?post_type=page
2. Yep will do.

**Comment by lukecav** [comment]
Waiting to be able to enable the WP Redis plugin again and enable debugging on the customer's site to get the info.

**Comment by stavultras** [comment]
Please try to use 1.1.1 version, there were some fixes about multiple keys caching, not sure if they fix your problem, but i think it's worth to try.

**Comment by lukecav** [comment]
@stavultras 
Version 1.1.1 version fixed the issue on the site.

**Comment by stavultras** [comment]
@lukecav good to know, thanks :)

**Comment by danielbachhuber** [comment]
@stavultras Double props to you — thanks again!
