### ISSUE TITLE
Retry logic for RedisException: "socket error on read socket" 

### ISSUE THREAD

**Issue by jtsternberg** [pantheon-systems/wp-redis#31]
This occurs for us occasionally. It might be good to try and reconnect if this error occurs? I don't know enough about the error to determine it's cause or the best solution for retrying, but posting it here.

**Comment by jtsternberg** [comment]
And by "occasionally", 12 times in the last week on a very high traffic site.

**Comment by danielbachhuber** [comment]
Hm. We could also make the retry exceptions filterable: https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L738
