### ISSUE TITLE
Allow filtering / removal of global cache groups

### ISSUE THREAD

**Issue by JanThiel** [pantheon-systems/wp-redis#330]
Hi there,

we have a setup where several of the `global_cache_groups` must not be global.
Currently there is no way to remove anything from the preconfigured global cache groups.

Global Cache Groups are set here as input from the outside:
https://github.com/pantheon-systems/wp-redis/blob/7dae4488e68ac71a40d7208581651e1ad758ac1b/object-cache.php#L425-L435

The only time global cache groups are set is this call in WP Core:

```php
	if ( function_exists( 'wp_cache_add_global_groups' ) ) {
		wp_cache_add_global_groups( array( 'users', 'userlogins', 'usermeta', 'user_meta', 'useremail', 'userslugs', 'site-transient', 'site-options', 'blog-lookup', 'blog-details', 'site-details', 'rss', 'global-posts', 'blog-id-cache', 'networks', 'sites', 'blog_meta' ) );
		wp_cache_add_non_persistent_groups( array( 'counts', 'plugins' ) );
	}
```
https://github.com/WordPress/WordPress/blob/e791d7f5db8252ba66c7777c456ed80343a450aa/wp-includes/load.php#L732-L735

There is no way of hooking into this process. No filters, nothing.
This might be due to the fact, that the caching happens early and WP isnt fully loaded.

To solve this we currently patched this code in the wp-redis object cache:
```php
if ( ! defined( 'WP_REDIS_DEFAULT_EXPIRE_SECONDS' ) ) {
        define( 'WP_REDIS_DEFAULT_EXPIRE_SECONDS', 0 );
}

if ( ! defined( 'WP_REDIS_IGNORE_GLOBAL_GROUPS' ) ) {
        define( 'WP_REDIS_IGNORE_GLOBAL_GROUPS', array() );
}
```

```php
        /**
         * Sets the list of global groups.
         *
         * @param array $groups List of groups that are global.
         */
        public function add_global_groups( $groups ) {
                $groups = (array) $groups;

                // Filter global groups
                $groups              = array_diff_key( $groups, WP_REDIS_IGNORE_GLOBAL_GROUPS );

                $groups              = array_fill_keys( $groups, true );
                $this->global_groups = array_merge( $this->global_groups, $groups );
        }

```

This allows one to configure an array of cache groups being disallowed as globals.
Due to the array in the constant it works only with PHP >7.

If there are smarter ways to solve this, we are not picky. Just looking for a reasonable working solution for this :-)

Thanks so far and best regards,
Jan

**Comment by danielbachhuber** [comment]
Thanks @JanThiel ! Great ticket 😄
