### ISSUE TITLE
[Feature Request] Work with WooCommerce

### ISSUE THREAD

**Issue by kevin25** [pantheon-systems/wp-redis#337]
Can you please make it work with WooCommerce?

**Comment by danielbachhuber** [comment]
Hey @kevin25,

WP Redis should work just fine with WooCommerce. It serves as a drop-in replacement for WordPress' internal object cache. As long as WooCommerce is interfacing with the object cache, WP Redis will handle the requests just fine.

**Comment by kevin25** [comment]
Thank you. How does it work with multiple stores in the same server? i got redirected to the same store.
