### ISSUE TITLE
PHP Fatal error: Cannot redeclare wp_cache_add()

### ISSUE THREAD

**Issue by sjoukedv** [pantheon-systems/wp-redis#341]
Hi,

The drop-in is throwing a fatal error;

```
PHP Fatal error: Cannot redeclare wp_cache_add()
(previously declared in /<path>/public/wp-content/object-cache.php:33) in /<path>/public/wp-includes/cache.php on line 30" 
```

The `wp_cache_add()` function is not mentioned in the [pluggable](https://codex.wordpress.org/Pluggable_Functions) functions. Nevertheless, several Redis plugins override this function (and it's siblings) inside a drop-in.

All help is appreciated!

**Comment by danielbachhuber** [comment]
Replied in the WordPress.org forums: https://wordpress.org/support/topic/wp_cache_add-cannot-be-redefined/
