### ISSUE TITLE
WP redis calling mysql...

### ISSUE THREAD

**Issue by erikdemarco** [pantheon-systems/wp-redis#342]
My site is faster with this plugin. But it could be much much faser if this plugin is not calling mysql for 'wp_redis_do_redis_failback_flush' EVERY single pageload. I dont understand what is the purpose of that? I succesfully managed to get my page to load only from object cache with zero mysql call. Just this 1 call hurting the performance.

**Comment by danielbachhuber** [comment]
Hey @erikdemarco,

Here's some of the history on the feature: https://github.com/pantheon-systems/wp-redis/pull/22

If you'd like to disable it, and understand the consequences of doing so, you can `define( 'WP_REDIS_DISABLE_WAKEUP_FLUSH', true );`

Hope this helps clarify!

**Comment by erikdemarco** [comment]
@danielbachhuber I see what you mean. But can't we just use something like try, catch block to detect error? Then if there is error we flush it. Instead of manually call sql every single load. Sql is really prone to race condition for big sites. Thats why most of them use cache to reduce mysql call.
