### ISSUE TITLE
Update Relay Cache mention to specify support

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-redis#350]
@tillkruss Can you submit a pull request against `readme.txt` with detail on the best way to get support for Relay?

There was an internal request along these lines that I previously missed:

> I wonder if we should request information on how to get support for Relay. Also, maybe the fact that this capability is available should be noted in the README? 
>
> ie: How end users would request support, that is, rather than have them ask us. A link to the GitHub issue queue, or wherever, for Relay would probably do).

**Comment by tillkruss** [comment]
Sure thing. In the same line as "Step 9"?

**Comment by danielbachhuber** [comment]
@tillkruss Yep, that would be great.
