### ISSUE TITLE
[BUG] redis database number setting doesnt work

### ISSUE THREAD

**Issue by erikdemarco** [pantheon-systems/wp-redis#356]
There is a commit in #273 made by @timnolte . But it doesnt work. 

Do you think just by adding 'database' to $redis_server it will automagically select the database number for us?
You need to select it manually after connection, see:
https://github.com/phpredis/phpredis#select

something like this:
```
$redis->connect();
$redis->select( $redis_server['database'] );
```

Maybe we need to do some kind of testing system before deploying the commit, not just blindly accept the commit.

Because of this all my website shared the same database number and causes error to all of them.

**Comment by timnolte** [comment]
@erikdemarco if you [look right here](https://github.com/pantheon-systems/wp-redis/pull/273/files#diff-7cc94ff6b911c98c86287bb4ab80d34f2673fac6f629c739b9cebd8a187fdc5aR33-R38) the database support was originally only half implemented prior to my change. Best to actually look at all of the code and how it works and not just at changed lines of code before throwing around accusations about things not being tested.

**Comment by timnolte** [comment]
@erikdemarco FYI, if you actually read through the code you will also see where this method is used to loop through the keys and establish the connection: https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L1238-L1253

And for your information I just connected to an instance where I have 5 WordPress installs, all variations of the same site, and all connecting to the exact same Redis instance, where a difference database number is provided for each site and there are all using different databases. You'd be wise to actually check your configuration to ensure that you have it configured correctly. If you aren't setting the `CACHE_DB` constant then that is your problem.

**Comment by erikdemarco** [comment]
@timnolte Ok lets we test it simple way:

First we set:
$redis_server = array(
	'host'     => '127.0.0.1',
	'port'     => 6379,
	'auth'     => '',
	'database' => 1,
);

Lets see this line:
https://github.com/pantheon-systems/wp-redis/blob/e825bc9535753e54e4a69e23b35565d0677e633d/object-cache.php#L1135

and we add this to those line:
var_dump( $this->redis->getDBNum() );

The var_dump result will always be 0. Do I miss something?
