### ISSUE TITLE
Blank Password Causing WP-CLI Failures, w/ PHP 8?

### ISSUE THREAD

**Issue by timnolte** [pantheon-systems/wp-redis#359]
https://wordpress.org/support/topic/blank-password-causing-wp-cli-failures-w-php-8/
> We use the WP-CLI during deployments and it seems as though with PHP 8 the plugin now causes problems with the WP-CLI when no password is used. We are getting exit failures when using the WP-CLI during our deployments that are causing them to fail.
```
wp stdout: Warning: WP Redis: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /public/wp-content/plugins/wp-redis/object-cache.php on line 1402
```

**Comment by timnolte** [comment]
Noting also that this seems the be an issue with the combination of PHP 8 and Redis 6.

**Comment by kevin25** [comment]
I got the same issue 



WP Redis: ERR AUTH called without any password configured for the default user. Are you sure your configuration is correct? |  
-- | --


<br class="Apple-interchange-newline">
