### ISSUE TITLE
Implement `wp_cache_flush_group`

### ISSUE THREAD

**Issue by spacedmonkey** [pantheon-systems/wp-redis#366]
Per https://core.trac.wordpress.org/ticket/4476

This would require adding an additional flush group on a per-cache-group basis.

Falling back to wp_cache_flush() would cause issues if a plugin on the main site attempted to flush a specific cache group, as it'd rotate every cache.

**Comment by spacedmonkey** [comment]
context https://github.com/rhubarbgroup/redis-cache/pull/399

**Comment by jspellman814** [comment]
This has been implemented in the 1.4.0 release. Please test that out and reopen this if you are still experiencing any issues. Thanks!
