### ISSUE TITLE
Implement `wp_cache_supports` function

### ISSUE THREAD

**Issue by spacedmonkey** [pantheon-systems/wp-redis#367]
Introduced in https://github.com/WordPress/wordpress-develop/commit/832b6c35f36d5f1ca84feadc49b0e5424af0ad6c.

**Comment by jspellman814** [comment]
We've released [1.3.1](https://github.com/pantheon-systems/wp-redis/releases/tag/1.3.1) which contains the fix for this. Please update to the latest version and let us know if you are still experiencing any issues. Thanks!

**Comment by tillkruss** [comment]
Closed via #382.
