### ISSUE TITLE
CircleCI is not configured correctly

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#374]
says

> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.

**Comment by jspellman814** [comment]
@szepeviktor Any chance you could clarify what you're looking for here? We don't ship CircleCI config with the plugin.

**Comment by szepeviktor** [comment]
The above message appears in PR-s. For example https://github.com/pantheon-systems/wp-redis/pull/373

And there is a configuration file for CircleCI
https://github.com/pantheon-systems/wp-redis/blob/master/.circleci/config.yml

**Comment by jspellman814** [comment]
I see, thank you! Since your PR is from a forked repository, it is not expected to run our CI.

**Comment by szepeviktor** [comment]
All right, all right.
(I run away)
