### ISSUE TITLE
PHP notice on Socket connection

### ISSUE THREAD

**Issue by gablau** [pantheon-systems/wp-redis#41]
Hi, 
when wp-redis is in socket configuration and you do not specify port parameter reise a php notice.

example config:
$redis_server = array( 'host' => '/tmp/redis.sock'); 

php Notice:
Notice: Undefined index: port in /var/www/vhosts/testsite.com/httpdocs/wp-content/object-cache.php on line 709

**Comment by danielbachhuber** [comment]
Thanks for the report! We'll get this fixed in v0.2.2
