### ISSUE TITLE
[CMSP-467] Please don't strip all tags from the cache password.

### ISSUE THREAD

**Issue by dgaastra** [pantheon-systems/wp-redis#431]
Thanks for developing such a great plugin and maintaining it.

I noticed a bug: commenting it out helped:

                                        'auth' => isset( $_SERVER['CACHE_PASSWORD'] ) ? /*wp_strip_all_tags(*/ $_SERVER['CACHE_PASSWORD']/* )*/ : '',

ERRORS:
[1] This corrupts our passwords and authentication fails. 
[2] If the CACHE_PASSWORD is provided as a user+pw pair, WP errors that it needs a string.

Thanks for looking into this.
Dennis

**Comment by pwtyler** [comment]
Thanks for the report! Tracking internally as CMSP-467. Looks like another unintended side-effect of #400.

**Comment by dgaastra** [comment]
Thanks and greetings from Bavaria
