### ISSUE TITLE
WP-CLI commands for cache manipulation

### ISSUE THREAD

**Issue by jtsternberg** [pantheon-systems/wp-redis#45]
Most interested in flushing, obviously, but a WP-CLI command API which closely mimics the redis-cli API would be pretty killer.

**Comment by danielbachhuber** [comment]
> Most interested in flushing, obviously

Why can't you use `wp cache flush` ?

> WP-CLI command API which closely mimics the redis-cli API would be pretty killer.

What's the advantage of replicating `redis-cli` in WP-CLI?

**Comment by jtsternberg** [comment]
> Why can't you use wp cache flush ?

Honestly, didn't know it existed. (Oops)

> What's the advantage of replicating redis-cli in WP-CLI?

In cases where the Redis connection strings are inaccessible. e.g. Settings are passed through environment variables.

**Comment by joshkoenig** [comment]
On Pantheon you can get connected to the Redis CLI via the dashboard.

But more generally having a `wp` command that can serve as a macro to launch the local `redis-cli` for the user could be neat.

**Comment by danielbachhuber** [comment]
> But more generally having a wp command that can serve as a macro to launch the local redis-cli for the user could be neat.

Yep. Or a wrapper, similar to [`wp db query`](http://wp-cli.org/commands/db/query/), which proxies commands with the connection details.

**Comment by jtsternberg** [comment]
Wrapper would be great but any/all sounds good to me.
Tangentially, If someone uses `flush` might be good to output an educational error stating that wp cache command should be used.
