### ISSUE TITLE
Add a status page in wp-admin

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp-redis#46]
It would be nice to have a status page in the wp-admin area that could tell if the cache is being used. When demoing I often forget to create the `object-cache.php` file, and a status page could tell me this. It could also present the data from Redis' `info` command.

**Comment by danielbachhuber** [comment]
> It would be nice to have a status page in the wp-admin area that could tell if the cache is being used.

Wouldn't this require activating the plugin, which isn't a part of the setup process?

> When demoing I often forget to create the `object-cache.php` file

In this case, had you activated the plugin?

**Comment by szepeviktor** [comment]
I've implemented a symlink maker in this halfdone plugin:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/ban/ban.php#L50-L111

**Comment by szepeviktor** [comment]
It is not on the back-end but: https://github.com/pantheon-systems/wp-redis/issues/47#issuecomment-183057460

**Comment by Angristan** [comment]
That would be a very cool feature indeed

**Comment by danielbachhuber** [comment]
This came up again in https://wordpress.org/support/topic/testing-if-object-caching-works/

Thinking a little status indicator like this would work:

![image](https://user-images.githubusercontent.com/36432/29287015-e22e41c4-80e8-11e7-8b90-abbb2015bf88.png)
