### ISSUE TITLE
Number of Objects Cached (Feature Addition request)

### ISSUE THREAD

**Issue by patademahesh** [pantheon-systems/wp-redis#47]
Can we add debug info like "W3 Total cache" where we can see information about Objects HIT and MISS ratio ?

Thank You.

**Comment by danielbachhuber** [comment]
:+1: dig it!

**Comment by danielbachhuber** [comment]
Here's a code snippet you can use to add hit and miss rate to your footer when logged in:

```
add_action( 'wp_footer', function(){
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	$GLOBALS['wp_object_cache']->stats();
});
```
