### ISSUE TITLE
Repo link

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#48]
Could you add repo URL here on GH?
https://wordpress.org/plugins/wp-redis/

**Comment by szepeviktor** [comment]
I've meant up here: https://github.com/pantheon-systems/wp-redis
There is an Edit link for repo admins.

**Comment by danielbachhuber** [comment]
Oh. I'm not sure what the language would be, as this `README.md` is the same that's used on WordPress.org.

**Comment by szepeviktor** [comment]
Please see:
![Edit](http://i.imgur.com/1c83ZQh.png)

**Comment by danielbachhuber** [comment]
Oh, I see what you're talking about.

@joshkoenig will be able to do that. I'm adding a link to the README too.

**Comment by szepeviktor** [comment]
Excuse me. The proper name (input placeholder) is `Website for this repository`

**Comment by joshkoenig** [comment]
Yeah! Will do now.

**Comment by szepeviktor** [comment]
@joshkoenig Thank you.
