### ISSUE TITLE
Meta headers

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#49]
WP reads meta headers from object-cache.php
Please consider adding some of these lines.

```php
/*
Plugin Name: 
Version: 
Description: 
Plugin URI: 
Author: 
*/
```

**Comment by szepeviktor** [comment]
At least version.

**Comment by danielbachhuber** [comment]
We removed plugin headers from `object-cache.php` in #25

**Comment by szepeviktor** [comment]
I would welcome the name though
```
/*
	Plugin Name: WP Redis
*/
```
See screenshot.

**Comment by danielbachhuber** [comment]
I believe any plugin headers would make the file available for activation, which introduces the original problem again.

**Comment by szepeviktor** [comment]
OH!! No other php files should be in plugin root!
Please consider moving `object-cache.php` to a subdir.

**Comment by danielbachhuber** [comment]
> Please consider moving object-cache.php to a subdir.

Doing so would break any existing symlinks, no?

**Comment by szepeviktor** [comment]
:( Yes

**Comment by szepeviktor** [comment]
Putting only the main php file in the plugin's root is *just* a general rule.
