### ISSUE TITLE
Several different WP installations

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#51]
Is it possible to use wp-redis with several different WP installations? (not a network)
I mean add support for redis DB-s.

**Comment by szepeviktor** [comment]
Is it #44?

**Comment by szepeviktor** [comment]
> # Users with setups where multiple installs share a common wp-config.php or $table_prefix
> # can use this to guarantee uniqueness for the keys generated by this object cache

Could it move to the README?

**Comment by szepeviktor** [comment]
`options:alloptions` key is not prefixed by WP core. Is it OK?

**Comment by danielbachhuber** [comment]
> Could it be revealed in README/Installation?

Yep, adding in #52
