### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#58]
[Plugin description](https://github.com/pantheon-systems/wp-redis/blob/master/wp-redis.php#L5) has an outdated link, the new one:
https://github.com/phpredis/phpredis

Could we have a note on `pecl install redis` for non-Panthen users?

**Comment by danielbachhuber** [comment]
> Plugin description has an outdated link, the new one:

Good catch. We'll get that fixed.

> Could we have a note on pecl install redis for non-Panthen users?

Given there are [multiple supported installation methods](https://github.com/phpredis/phpredis#installingconfiguring), I don't think it makes sense to highlight a specific one.

**Comment by szepeviktor** [comment]
https://github.com/phpredis/phpredis has no word about PECL :(

**Comment by szepeviktor** [comment]
Till the next fix!
