### ISSUE TITLE
Allow persistent connections to Redis

### ISSUE THREAD

**Issue by jtsternberg** [pantheon-systems/wp-redis#64]
Would like the ability to use [`Redis::pconnect`](https://github.com/phpredis/phpredis#pconnect-popen) vs `Redis::connect`.

**Comment by danielbachhuber** [comment]
Seems pretty straightforward. What's the advantage of pconnect in your use case?

**Comment by jtsternberg** [comment]
It was recommended for us by the team at Azure. I'm not entirely sure of the reasoning, other than the idea of limiting the number of re-connections.

**Comment by jtsternberg** [comment]
Submitted PR (#73) in hopes that this would be addressed soon. Thank you.

**Comment by danielbachhuber** [comment]
Given the conversation in #73, it doesn't seem like we're going to pursue this feature.
