### ISSUE TITLE
Old version in plugin

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#67]
@danielbachhuber Please consider creating a release checklist in the Wiki

Still 0.2 in https://github.com/pantheon-systems/wp-redis/blob/master/wp-redis.php#L6

**Comment by szepeviktor** [comment]
https://wordpress.org/plugins/wp-redis/ shows 0.2 and link the 0.3 zip.

**Comment by danielbachhuber** [comment]
> https://wordpress.org/plugins/wp-redis/ shows 0.2 and links the 0.3 zip.

Fixed. Thanks for catching that.

> Please consider creating a release checklist in the Wiki

Eh, it's pretty simple:

1. Update the changelog
2. Update the stable versions
3. Release on WordPress.org
4. Tag a release on Github

A mistake like this is simple enough that it's possible to miss even when it's in the release checklist.

**Comment by szepeviktor** [comment]
1.    Update the changelog
1.    Update the stable version in readme
1.    Update the stable version in wp-redis.php
1.    Release on WordPress.org
1.    Tag a release on Github
