### ISSUE TITLE
Ensure default cache group is always 'default'

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-redis#69]
The signature for `wp_cache_add()`:

```
function wp_cache_add( $key, $data, $group = '', $expire = 0 ) {`
```

The signature for `WP_Object_Cache->add()`:

```
public function add( $key, $data, $group = 'default', $expire = 0 ) {
```

WordPress core has the following within its methods so that `$group` is never empty:

```
if ( empty( $group ) )
	$group = 'default';
```

We, however, do not.

Related #68

**Comment by joshkoenig** [comment]
Possible bugfix to core also? Seems weird that the two methods don't have the same signature, and that there's additional logic further downline to normalize them...

**Comment by danielbachhuber** [comment]
> Possible bugfix to core also? Seems weird that the two methods don't have the same signature, and that there's additional logic further downline to normalize them...

Welcome to WordPress :)

I don't think this is worth attempting to fix in core because, in my opinion, its the type of seemingly innocent change that will cause something to explode.
