### ISSUE TITLE
WP Pantheon Cache on Multisite does not clear Redis

### ISSUE THREAD

**Issue by aeligature** [pantheon-systems/wp-redis#72]
Clearing cache via Pantheon Cache does not appear to do anything within a WP multisite site.

Steps to reproduce:

Create a super admin WP user for a multisite in Live:
`
ex: terminus wp "user create csecse2 pantheor@getpantheon.com --user_pass=manticore --role=administrator" --site=candela --env=live`

`terminus wp "super-admin add csecse2" --env=live --site=candela`

Connect to redis-cli for the multisite in Live, run:

`ex: KEYS "49:*"`

substitute the number in KEYS for the site multisite with actual keys

clear cache on the page in the site via Pantheon Cache

then run `KEYS "49:*"` again

there are no cleared keys.

```
104.239.201.36:11983> dbsize
(integer) 3406
```

Clearing the caches through the dashboard resulted in an actual clear:

```
[2:56] 
104.239.201.36:11982> dbsize
(integer) 0
```

**Comment by danielbachhuber** [comment]
> Clearing cache via Pantheon Cache does not appear to do anything within a WP multisite site.

I think that this is because the Pantheon Cache UI doesn't touch the WordPress object cache. https://github.com/pantheon-systems/WordPress/issues/69 would do the trick, if we want to change the behavior.

**Comment by danielbachhuber** [comment]
This is being handled in https://github.com/pantheon-systems/WordPress/pull/69
