### ISSUE TITLE
Fail gracefully if config is missing

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp-redis#8]
Currently this dies pretty hard if the expected configuration isn't there. It should have a developer/user friendly exception handler so that people are guided to configure the plugin.

**Comment by danielbachhuber** [comment]
@joshkoenig Happy with the implementation? Close if it's :ship:, or let me know how you'd like the experience refined?

**Comment by joshkoenig** [comment]
Will test this today and let you know. Thanks!
