### ISSUE TITLE
Compatibility with Batcache?

### ISSUE THREAD

**Issue by tlovett1** [pantheon-systems/wp-redis#80]
Is this plugin compatible with Batcache?

**Comment by danielbachhuber** [comment]
Compatible in what sense? It should be fine to run the two side by side.

**Comment by szepeviktor** [comment]
Maybe: Will Batcache put pages in wpcache thus in redis?

-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by tlovett1** [comment]
Here is the error I'm getting:

`Fatal error: Call to undefined function add_action() in /srv/www/trunk/wp-content/object-cache.php on line 1087`

Clearly, Batcache is instantiating WP_Object_Cache before `add_action` is available. I can fix if you guys want.

**Comment by danielbachhuber** [comment]
> Clearly, Batcache is instantiating WP_Object_Cache before add_action is available.

Huh.

>  I can fix if you guys want.

What do you think the fix should be?

**Comment by tlovett1** [comment]
https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L74

`advanced-cache.php` is included before things like `$wpdb` or `add_action()` are defined.

**Comment by tlovett1** [comment]
The fix is getting rid of the "failback" flush as well as the admin notice error. If you guys are interested, I can create a PR.

**Comment by danielbachhuber** [comment]
> The fix is getting rid of the "failback" flush as well as the admin notice error.

Er, removing a feature isn't really a fix. We'll need to find some other workaround.

**Comment by danielbachhuber** [comment]
Similar to how Batcache does it, we can inject our action instead on the `$wp_filter` global: https://github.com/Automattic/batcache/blob/master/advanced-cache.php#L540

Alternatively, because the object cache is always re-initialized after advanced-cache.php runs, we could just have safety checks for `add_action()` and `$wpdb` being defined.

**Comment by danielbachhuber** [comment]
@tlovett1 Can you see if #81 works for your needs?

**Comment by josephabrahams** [comment]
Works like  a charm!

**Comment by danielbachhuber** [comment]
🔨
