### ISSUE TITLE
Can we remove `exists` calls to Redis?

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-redis#85]
On WordPress sites heavily utilizing the object cache, the `exists` calls essentially double the number of network requests on a given page load. Can we remove these calls to reduce the number of network requests?

**Comment by danielbachhuber** [comment]
@mboynes Do you recall why these were added in the first place? I'm referring to:

* https://github.com/pantheon-systems/wp-redis/commit/c8486576b0d55552570a678998a68e55a8ea1f56#diff-5a2b681f0d32956de83215ea32388177R400
* https://github.com/pantheon-systems/wp-redis/commit/c8486576b0d55552570a678998a68e55a8ea1f56#diff-5a2b681f0d32956de83215ea32388177R444

**Comment by danielbachhuber** [comment]
From Slack conversation with Matt:

> mboynes [10:09 AM] hmm, there was a reason for it
> [10:09] but I'm blanking
> [10:10] I'd say, if you can remove them and everything continues to work, :+1:
> danielbachhuber [10:10 AM] hehe
> [10:10] I think I might try the refactor and see what breaks
> [10:10] I feel pretty good about the text coverage
> mboynes [10:10 AM] benchmark it too
> danielbachhuber [10:11 AM] oh, I've already benchmarked it
> mboynes [10:11 AM] also make sure you're benchmarking a cold cache as well as a warm one
> danielbachhuber [10:11 AM] it's the source of some perf issues, because it essentially doubles the network traffic
> [10:12] cold redis cache?
> mboynes [10:12 AM] yeah, because these methods will bail quicker if the key doesn't exist
> [10:13] so there are circumstances where this will improve performance
> [10:13] obviously there are circumstances where it degrades performance, as you're noting
> [10:14] I have no idea where the tipping point is going to be on that
> danielbachhuber [10:14 AM] huh
> mboynes [10:15 AM] another gotcha is, if a `null` value is cached, can you discern between a cache hit and a cache miss if you don't check `exists`?
> danielbachhuber [10:16 AM] I don't think you can cache `null`
> mboynes [10:16 AM] oh, no? that's easy then if that's the case
> danielbachhuber [10:16 AM] https://github.com/pantheon-systems/wp-redis/pull/79/commits/b358c05fe79235d92dce9ddb0f06390eb8a53c3d
> mboynes [10:16 AM] ah
> [10:17] oh right
> [10:18] it's been a long time since I worked with redis
> [10:18] or this plugin
> [10:18] I forgot you only store strings, so I worked around that with serialization

**Comment by danielbachhuber** [comment]
@joshkoenig @stevector Looking at the other methods:

* `incr()` and `decr()` require the `exists` check because WordPress' behavior is to return false if the key doesn't yet exist, while Redis' behavior is to create a new key and increment it.
* `delete()` doesn't _necessarily_ need the `exists` check, but there's existing "force" behavior we'd need to deprecate in order to remove it.
* `replace()` doesn't have an equivalent Redis command, so we need to call `exists` and `set`.
* `set()` doesn't call `exists`.

Given removing `exists` from the `get()` method yielded the greatest performance benefits, I think we can call this 🚢

**Comment by joshkoenig** [comment]
Woot!
