### ISSUE TITLE
Unknown URI scheme "unix"

### ISSUE THREAD

**Issue by FabianGabor** [pantheon-systems/wp-redis#86]
Having this error in HHVM at every connection:

[Mon Apr 18 20:29:39 2016] [hphp] [24355:7fe0ab7ff700:2:000001] [] \nWarning: Unknown URI scheme "unix" in /wp-content/object-cache.php on **line 948**

Fixed it by commenting out the IF statement and leaving only the $port = null;

**Comment by szepeviktor** [comment]
What is the value of your `'host'`?
