### ISSUE TITLE
Warn user on activation if on Pantheon and the Redis service isn't turned on

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp-redis#9]
Similar to what we do in our Solr plugin.

**Comment by danielbachhuber** [comment]
We probably should include this warning in the Pantheon WordPress upstream.

**Comment by danielbachhuber** [comment]
@joshkoenig After #9, we can add an action to `admin_notices` early to inspect `$wp_object_cache->$this->missing_redis_message` and customize the message specific to Pantheon.

Out of the box, the message would be:

> Alert! WP Redis object cache cannot connect to Redis server.

**Comment by joshkoenig** [comment]
Ok, sounds interesting. I like the idea of separating the generic warning from the platform specific one. Perhaps we should do the same for our Solr plugin too.

**Comment by danielbachhuber** [comment]
@joshkoenig assigning to you for a final review and close if you're happy with the messaging text.

**Comment by joshkoenig** [comment]
This is good. We may do another pass in the future to standardize language across multiple cases (as well as documenting the causes of the errors) but I'm good with this now. The goal was "no inexplicable WSOD" and we've achieved that. :)
