### ISSUE TITLE
Consider serializing null value before saving to Redis

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-redis#96]
Because Redis coerces `null` to an empty string (https://github.com/pantheon-systems/wp-redis/pull/95/commits/a0b54a9eff8c6e777a6b635053ede72b9429e2db#diff-137263c87da66ee3f3f8b75e064fdeb8R440), our existing behavior is a bit lossy. We should consider serializing a `null` value so that it retains its true form.

**Comment by danielbachhuber** [comment]
Although, something to consider is that `N;` becomes a magical string in Redis, and would always deserialize regardless of whether it was originally `null`.

**Comment by ssnepenthe** [comment]
> `N;` becomes a magical string in Redis

Do you have any more info on this? I have been having trouble finding anything.

It looks like `null` is actually serialized here:

```
if ( ! is_numeric( $data ) || intval( $data ) !== $data ) {
    $data = serialize( $data );
}
```

before saving to Redis but is converted to an empty string in `->_set_internal()`.

**Comment by danielbachhuber** [comment]
> Do you have any more info on this? I have been having trouble finding anything.

I think this was an incorrect assumption on my part.

Based on what you identified, it seems like the problem is easier: we shouldn't convert to an empty string in `->_set_internal()`.

**Comment by ssnepenthe** [comment]
Good deal - that likely means some updates around the use of `isset()` as well.

I can take a closer look a little later this morning if you'd like.

**Comment by danielbachhuber** [comment]
Sure!

**Comment by ssnepenthe** [comment]
Done.

I also updated a couple of test assertions that were checking for a null value when the cache entry doesn't exist. I hope that's alright...
